language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-28
  licences:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - cd application/
  - ./gradlew build
